# Generated by Django 3.2.7 on 2022-01-12 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course',
        ),
        migrations.DeleteModel(
            name='subject',
        ),
    ]
