# Generated by Django 3.2.7 on 2022-01-13 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20220113_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_app',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
