# Generated by Django 3.2.7 on 2022-01-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20220113_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='material',
            field=models.FileField(blank=True, null=True, upload_to='study_material'),
        ),
    ]
