# Generated by Django 3.2.7 on 2022-01-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_course_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='material',
            field=models.CharField(default='jkl', max_length=1000),
            preserve_default=False,
        ),
    ]
