# Generated by Django 3.2.7 on 2022-01-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_course_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='userCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idn', models.IntegerField()),
                ('user', models.CharField(max_length=100)),
                ('courseName', models.CharField(max_length=300)),
            ],
        ),
    ]
