# Generated by Django 3.2.7 on 2022-01-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_usercourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='courseName',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='user',
        ),
        migrations.AddField(
            model_name='usercourse',
            name='nm',
            field=models.CharField(default='sss', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercourse',
            name='un',
            field=models.CharField(default='w', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='idn',
            field=models.CharField(max_length=200),
        ),
    ]
