# Generated by Django 3.2.7 on 2022-01-17 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_certificate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='course',
            new_name='course_name',
        ),
    ]
