# Generated by Django 3.2.7 on 2022-01-17 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_rename_course_certificate_course_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='course_name',
            new_name='course',
        ),
    ]
